### ISSUE TITLE
Identity resolution playbook (collab w/ Census)

### ISSUE THREAD

**Issue by krevitt** [dbt-labs/devhub-writing#4]
Draft + notes here:
https://docs.google.com/document/d/1L524mzAD72zRs2lhye4ArWxjfDwOYpOLKSuC9PiDJaE/edit#

Playbooks to live within the technical blog (docs.getdbt.com/blog), if we can swing it by first couple weeks of October.

**Comment by amychen1776** [comment]
@krevitt Just checking here that you don't need any assistance from me on this because of the partnerships aspect here

**Comment by krevitt** [comment]
> @krevitt Just checking here that you don't need any assistance from me on this because of the partnerships aspect here

just received a draft on this (linked in the project) - welcome to read it if you like and we'll discuss at office hours tomorrow - it's a pretty standard dbt playbook (for customer 360 modeling)

**Comment by dflynn20** [comment]
Hey @krevitt @amychen1776 @jasnonaz , following up with the polished draft here:
https://docs.google.com/document/d/14787eQzv6jaluXLW6LLZhKRDsgT4S3vAhShatSnB7DI/

Allie gave it a couple of passes, but I am very open to feedback!

Repo is linked in the doc but is also here: https://github.com/dflynn20/jaffle_gaggle

**Comment by krevitt** [comment]
Thanks @dflynn20!  A few of us on the team (@jasnonaz @patkearns10 @graciegoheen) spent some time reading + left a bunch of comments.

Think our overall feedback could be summarized as:
- Starting with "why" could be helpful, to frame (in both the intro + each section) why someone would want to do the thing. Why's someone need identity resolution for PLG, and what are the 3-4 key things that they'd do with this info that otherwise would be hard?  You got to that "why" in the conclusion and often at the end of sections - think moving those bits front and center would help hook readers into each section.
- On the "why", Pat was curious how is this different or a better version of slowly changing dimension on your models? 
- The JaffleGaggle example is really complex!  I wonder if you could simplify the metaphor there to not lose focus on why this type of modeling is useful.  We found ourselves straining to put the pieces together on the metaphor.
- More signposting + context would be helpful - might be useful to lay out in the intro the few steps you'll work through here and why they're important?  Would help orient readers as they're working through it.
- Clearer section header names could help w/ signposting (the "in the loop" framing is a bit insider-y to be easily understood by new readers).  

Hope those points are helpful!  Happy to riff on them here or in the doc as y'all like.

**Comment by alliemdbd** [comment]
Hey @krevitt! Thanks so much for the feedback - Donny and I met today and will work on a 2.0 version to send over later this week.

**Comment by dflynn20** [comment]
Hi @krevitt, 

@alliemdbd and I went through it and addressed all of the points.

As for Pat's point about slow-changing dimensions, I don't believe this applies to CRM data as you would want to have the current data to reference for sales reach-outs. With this and taking into account that this is a sandbox / playground project with static data, I chose to not add it.

Excited to get your feedback on where it is now. Thanks for the detailed read through and notes and Happy 2022! 🎆

**Comment by krevitt** [comment]
Looks great on a first pass!  Will drop some more detailed comments in tomorrow, but generally this is in great shape

**Comment by alliemdbd** [comment]
@krevitt awesome! Glad to hear it's looking good and we'll keep an eye out for edits. 

also, wanted to get you and the community/partner folks' opinion on possibly rolling this into a fun little campaign for early Feb. It would mean holding the publication until early Feb, but would be a fun awareness/ABM campaign to play on the Jaffle lore. Would include: 
- The playbook itself (living on dbt’s dev blog)
- Donny’s README of the project from his GitHub living on a microsite (jaffleshop.io or something)
- A “sync-a-jaffle” ABM push where folks can use the Census sync-a-swag feature to send themselves a jaffle maker and we send them over to this playbook/the dbt blog 
- A Census Operational Analytics Club community event with Claire on how to make Jaffles or some such fun topic (again pointing toward the microsite/the blog) 
- Lead sharing of course :) 

Sounds like Claire is tentatively down for it for early Feb. Wdyt?

**Comment by krevitt** [comment]
Hey @alliemdbd just checked in w/ the team - we're of course happy to promote the post, but doesn't look like the team has bandwidth for a full campaign in feb.

**Comment by krevitt** [comment]
Hey @dflynn20 just gave the post a full readthrough - great stuff!  Left some comments in spots that could use more clarification, but in general this is making a lot of progress and think we're close to good to go here.

**Comment by alliemdbd** [comment]
Hey @krevitt  thanks for checking! We'd be doing all the heavy lifting for it. The only thing we'd ask for some help with is sharing out to your networks when we promote (and, of course, publishing the blog post above). Does that sound more doable?

**Comment by dflynn20** [comment]
Hey @krevitt , we just went through and polished up the piece. Thanks for the feedback!

One other note: this code is living under my user, I wanted to see if it makes the most sense to keep it there? I'm happy to move it, just let me know!

**Comment by alliemdbd** [comment]
Hey @krevitt just bumping this. Thanks :)

**Comment by krevitt** [comment]
Thanks for the bump Allie!  On those questions:

> One other note: this code is living under my user, I wanted to see if it makes the most sense to keep it there? I'm happy to move it, just let me know!

Hey @dflynn20, my hunch is that it's ok to leave on your personal profile (to convey that you're the author) - don't see any downside to leaving it there.

> Hey @krevitt thanks for checking! We'd be doing all the heavy lifting for it. The only thing we'd ask for some help with is sharing out to your networks when we promote (and, of course, publishing the blog post above). Does that sound more doable?

In the limited non-partnership-team scope of what I work on, I can say we'll definitely promote the post, and that could take the form of RTing something that you post that also includes other jaffle-centric stuff.

**Comment by alliemdbd** [comment]
Hey @krevitt sounds good! We're looking at a Feb. 8 date. Would it be possible to publish the playbook that week (on the 7th) and we'll drive some traffic there from our side?

**Comment by krevitt** [comment]
Yes let's do that, will set it up for the 7th

**Comment by krevitt** [comment]
@alliemdbd @dflynn20 PR is [up here](https://github.com/dbt-labs/docs.getdbt.com/pull/1091), you can [view a preview of the post here](https://deploy-preview-1091--docs-getdbt-com.netlify.app/blog/customer-360-view-identity-resolution)!

Left a [few notes on the draft](https://docs.google.com/document/d/14787eQzv6jaluXLW6LLZhKRDsgT4S3vAhShatSnB7DI/edit#) of sections I trimmed during publishing - think given the level of detail in comments in the repo, we could leave some of that out of the full post without sacrificing technical detail.
