### ISSUE TITLE
dbt utils overview and most used functions

### ISSUE THREAD

**Issue by jasnonaz** [dbt-labs/devhub-writing#9]

**Comment by JoshuaSmart-Olufemi** [comment]
Hi there. My name's Josh and I'd love to look into developing this topic into an article members of the dbt community can learn from.

**Comment by JoshuaSmart-Olufemi** [comment]
Hi @jasnonaz . Here's the Google Doc link to the article for review. https://docs.google.com/document/d/1AaZpvhVE7lbRaU7sDs64gJPgJjCILqgo4kyhVJulBp0/edit?usp=sharing

**Comment by gwenwindflower** [comment]
per above closing in favor of this discussion https://github.com/dbt-labs/docs.getdbt.com/discussions/1139
